server:
  port: 8081
logging:
  level:
    org.springframework.web: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kotlin_search
      repositories:
        type: auto